/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel; 
import javax.swing.ViewportLayout;
/**
 *
 * @author Aqib Rehman
 */
public class UsersManagement extends javax.swing.JFrame {

    /**
     * Creates new form UsersManagement
     */
     DefaultTableModel model1;
      FramesEntity fe;
     
    public UsersManagement() {
        
        
        initComponents();
        
         fe = new FramesEntity();
//        JCheckBox cb1 = new JCheckBox("CheckBox1 ");
//                                    
//                                    jpanel_checkboxes.add(cb1);
//                                    jpanel_checkboxes.revalidate();
//                        jpanel_checkboxes.repaint();
                        
//                        jlist_checkboxes.setCellRenderer(new CheckboxListCellRenderer());
//                        framesRender();
                       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txt_userName = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jpanel_checkboxes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist_checkboxes = new javax.swing.JList();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("User Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 12, -1, -1));

        jLabel2.setText("User Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 60, -1, -1));

        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 98, -1, -1));

        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 137, -1, -1));

        jLabel5.setText("User Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 175, -1, -1));

        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 57, 73, -1));
        jPanel1.add(txt_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 95, 132, -1));
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 134, 134, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMIN", "USER" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 172, 107, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Accounts");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jLabel7.setText("Permission");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 53, -1, -1));

        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 12, 88, -1));

        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 50, 88, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 205));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 81, 65, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 205));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DELETE");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 81, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 205));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DEL ALL");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 81, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ADD ALL");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 81, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 225, 330, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Products");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jLabel9.setText("Permission");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 53, -1, -1));

        jPanel3.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 12, 88, -1));

        jPanel3.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 50, 88, -1));

        jButton5.setBackground(new java.awt.Color(51, 51, 205));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ADD");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 81, 65, -1));

        jButton6.setBackground(new java.awt.Color(51, 51, 205));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("DELETE");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 81, -1, -1));

        jButton7.setBackground(new java.awt.Color(51, 51, 205));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("DEL ALL");
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 81, -1, -1));

        jButton8.setBackground(new java.awt.Color(51, 51, 205));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("ADD ALL");
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 81, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 330, 110));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel_checkboxes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlist_checkboxes.setBackground(new java.awt.Color(240, 240, 240));
        jlist_checkboxes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlist_checkboxes.setAlignmentX(1.5F);
        jlist_checkboxes.setAlignmentY(1.5F);
        jScrollPane2.setViewportView(jlist_checkboxes);

        jpanel_checkboxes.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 174, 380));

        jPanel4.add(jpanel_checkboxes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 194, -1));

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("ADD");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 78, -1));

        jButton10.setBackground(new java.awt.Color(102, 102, 102));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("DELETE");
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 420, 78, -1));

        jButton11.setBackground(new java.awt.Color(102, 102, 102));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("CLEAR");
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 420, 78, -1));

        jButton12.setBackground(new java.awt.Color(102, 102, 102));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("UPDATE");
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 420, -1, -1));

        jButton13.setBackground(new java.awt.Color(102, 102, 102));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("BACK");
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 450, 78, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 51, 149, 363));

        jLabel10.setText("Users");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 26, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 28, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
      String userName =   txt_userName.getText().toString();
//      String password =   txt_password.toString();
     String password =  new String(txt_password.getPassword());
        DefaultListModel model = new DefaultListModel();
      model = (DefaultListModel) jlist_checkboxes.getModel();
      List frames = fe.getAllFrames();
       for (int i = 0; i < frames.size(); i++) {
                //ch[i]=new JCheckBox("CheckBox"+i);
//                model.addElement(new CheckListItem("CheckBox"+i));
//                model.addElement(new CheckListItem(frames.get(i)));
//           model.getElementAt(i);
           
            CheckListItem item = (CheckListItem)
                       model.getElementAt(i);
           if(item.isSelected()){
               String frameName = item.toString();
           
            System.out.println("****"+frameName);
           }
            }
       System.out.println("****"+userName);
       System.out.println("****"+password);
       
         try {
             java.util.Vector v=DatabaseManager.getProduct();
         } catch (Exception ex) {
             ex.printStackTrace();
         }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            throw ex;
//         } catch (InstantiationException ex) {
//        throw ex;
//         } catch (IllegalAccessException ex) {
//        throw ex;
//         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//        throw ex;
//         }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               UsersManagement um = new UsersManagement();
               um.framesRender();
//               um.revalidate();
               um.setVisible(true);
            }
        });
    }
    
    public void framesRender(){
     
        
        
//         String[]labels={"a","b","c","d","e"};
//            JCheckBox[]ch=new JCheckBox[labels.length];
         
         List frames = fe.getAllFrames();

            final DefaultListModel model = new DefaultListModel();
jlist_checkboxes.setModel(model);
//            JList list=new JList(model);
            jlist_checkboxes.setCellRenderer(new CheckboxListCellRenderer());
            for (int i = 0; i < frames.size(); i++) {
                //ch[i]=new JCheckBox("CheckBox"+i);
//                model.addElement(new CheckListItem("CheckBox"+i));
                model.addElement(new CheckListItem(frames.get(i).toString()));
            }
            
            
            jlist_checkboxes.addMouseListener(new MouseAdapter()
            {
                 public void mouseClicked(MouseEvent event)
                 {
                    JList list = (JList) event.getSource();
                    // Get index of item clicked
                    int index = list.locationToIndex(event.getPoint());
                    CheckListItem item = (CheckListItem)
                       list.getModel().getElementAt(index);
                    // Toggle selected state
                    item.setSelected(! item.isSelected());
                    // Repaint cell
                    list.repaint(list.getCellBounds(index, index));
                 }
            }); 
            
            
            
//        DefaultListModel listModel = new DefaultListModel();
//for (int i = 0; i < 7; i++)
//{
//    JCheckBox[] checkBoxList = new JCheckBox[numberCheckBox];
//    listModel.addElement("aa");
//}
//jlist_checkboxes.setModel(listModel);
        
   
//DefaultListModel listModel1 = new DefaultListModel();
// int numberCheckBox = 5;
// JCheckBox[] checkBoxList = new JCheckBox[numberCheckBox];
//for(int i = 0; i < numberCheckBox; i++) {
////    checkBoxList[i] = new JCheckBox("CheckBox" + i);
//     JCheckBox checkBox2 = new JCheckBox("Checkbox 2", true);
//     
//listModel1.addElement(checkBox2);
//}
//jlist_checkboxes.setModel(listModel1);
        
//        int numberCheckBox = 5;
//JCheckBox[] checkBoxList = new JCheckBox[numberCheckBox];
//
//for(int i = 0; i < numberCheckBox; i++) {
//    checkBoxList[i] = new JCheckBox("CheckBox" + i);
//    jpanel_checkboxes.add(checkBoxList[i]);
//    jpanel_checkboxes.repaint();
//}

        
        // set flow layout for the frame
//        this.getContentPane().setLayout(new FlowLayout(FlowLayout.TRAILING, 50, 20)); //(default) centered alignment and a default 5-unit horizontal and vertical gap.

//        JCheckBox checkBox1 = new JCheckBox("Checkbox 1");
//        checkBox1.setSelected(true);
//
//        JCheckBox checkBox2 = new JCheckBox("Checkbox 2", true);
//
//        JCheckBox checkBox3 = new JCheckBox("Checkbox 3");
//
//        // add checkboxes to frame
//
//        jpanel_checkboxes.add(checkBox1);
//
//        jpanel_checkboxes.add(checkBox2);
//        jpanel_checkboxes.add(checkBox3);
//
//        pack();
        
        
//          model1 = new DefaultTableModel(){
//            public Class <?>getColumnClass(int column){
//                switch (column){
//                    case 0:
//                    return String.class;
//                    default:
//                    return String.class;
//                }
//            }
//        };
//        //    tbl_items.setModel(new DefaultTableModel(rows, columnNames));
//        tbl_items.setModel(model1);
//    
//        Vector rows  = new Vector();
//        Vector columnNames = new Vector();
//        columnNames.addElement("Flight Id");
//        columnNames.addElement("Flight Type");
//        columnNames.addElement("From");
//        columnNames.addElement("To");
//        columnNames.addElement("Departure Time");
//        columnNames.addElement("Arrival Time");
//        columnNames.addElement("Seats Available");
//        columnNames.addElement("Cost");
//        columnNames.addElement("Total Time");
//        columnNames.addElement("Select");
//        
//        model1.addColumn("Flight Id");
//        model1.addColumn("Flight Type");
//        model1.addColumn("From");
//        model1.addColumn("To");
//        model1.addColumn("Departure Time");
//        model1.addColumn("Arrival Time");
//        model1.addColumn("Seats Available");
//        model1.addColumn("Cost");
//        model1.addColumn("Total Time");
//        model1.addColumn("Select"); 
//        
//        for(int i=0; i<fel1.size();i++){
//
//            Vector <Object> newRow = new Vector <Object>();
////            newRow.addElement(ci.getValue());
//            newRow.addElement(fel1.get(i).getId().toString());
//            newRow.addElement(fel1.get(i).getFlightType());
//            newRow.addElement(fel1.get(i).getFrom());
//            newRow.addElement(fel1.get(i).getTo());
//            newRow.addElement(fel1.get(i).getDepartureTime());
//            newRow.addElement(fel1.get(i).getArrivalTime());
//            newRow.addElement(fel1.get(i).getSeats());
//            newRow.addElement(fel1.get(i).getCost());
//            newRow.addElement(fel1.get(i).getHrs());
//            //        String idIs = resturantEntity.getMenuItemList().get(i).getId().toString();
//            //        Checkbox c1 = new Checkbox();
//            //        c1.setName(idIs);
//            newRow.addElement(Boolean.FALSE);
////            newRow.addElement("0");
//            
//            rows.addElement(newRow);
//            model1.addRow(newRow);
//        }
        
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList jlist_checkboxes;
    private javax.swing.JPanel jpanel_checkboxes;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables
}
